# Generated by Django 6.0.1 on 2026-04-25 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email alerts'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='temperature_alert_threshold',
            field=models.FloatField(blank=True, default=None, help_text='Alert if temperature exceeds this value (Celsius)', null=True),
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temp_above', 'Temperature Above'), ('temp_below', 'Temperature Below'), ('humidity_above', 'Humidity Above'), ('humidity_below', 'Humidity Below'), ('wind_above', 'Wind Speed Above'), ('pressure_above', 'Pressure Above'), ('pressure_below', 'Pressure Below')], max_length=20)),
                ('threshold_value', models.FloatField(help_text='Threshold value for the alert')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weather_app.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
